import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { praatPitchAc, PRAAT_PITCH_DEFAULTS, smoothOctaves } from '../src/plugins/signal/praatPitch.ts'

// Gold-standard comparison: our JS port of Praat's AC pitch vs Praat 6.6's own output on a real
// 10 s speech segment. Fixtures generated by scripts/praat_wav_reference.praat (committed under
// tests/fixtures/praat/). If the fixtures are absent (not generated), the suite is skipped.

const dir = resolve(process.cwd(), 'packages/media-player/tests/fixtures/praat')
const wavPath = resolve(dir, 'seg_mono.wav')
const csvPath = resolve(dir, 'seg_pitch.csv')
const haveFixtures = existsSync(wavPath) && existsSync(csvPath)

function readWavMono(path: string): { sampleRate: number; samples: Float32Array } {
  const buf = readFileSync(path)
  if (buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WAVE') throw new Error('not a WAV')
  let pos = 12, sampleRate = 0, bits = 16, channels = 1
  let samples = new Float32Array(0)
  while (pos + 8 <= buf.length) {
    const id = buf.toString('ascii', pos, pos + 4)
    const size = buf.readUInt32LE(pos + 4)
    const body = pos + 8
    if (id === 'fmt ') { channels = buf.readUInt16LE(body + 2); sampleRate = buf.readUInt32LE(body + 4); bits = buf.readUInt16LE(body + 14) }
    else if (id === 'data') {
      const bytesPerSample = bits / 8, frames = Math.floor(size / (bytesPerSample * channels))
      samples = new Float32Array(frames)
      for (let f = 0; f < frames; f++) {
        // mono fixture (channels === 1); if stereo, average.
        let acc = 0
        for (let c = 0; c < channels; c++) {
          const o = body + (f * channels + c) * bytesPerSample
          acc += bits === 16 ? buf.readInt16LE(o) / 32768 : buf.readInt32LE(o) / 2147483648
        }
        samples[f] = acc / channels
      }
    }
    pos = body + size + (size & 1)
  }
  return { sampleRate, samples }
}

function readPitchCsv(path: string): { time: number; f0: number }[] {
  return readFileSync(path, 'utf8').trim().split('\n').slice(1).map(line => {
    const [t, f] = line.split(',')
    return { time: parseFloat(t!), f0: parseFloat(f!) }
  })
}

describe('smoothOctaves', () => {
  it('fixes isolated octave errors, keeps steady pitch and unvoiced gaps', () => {
    const base = 150
    const f0 = new Float32Array(20).fill(base)
    f0[5] = base * 2      // octave-up error
    f0[12] = base / 2     // octave-down error
    f0[8] = 0             // unvoiced
    const out = smoothOctaves(f0)
    expect(out[5]).toBeCloseTo(base, 3)
    expect(out[12]).toBeCloseTo(base, 3)
    expect(out[8]).toBe(0)
    for (let i = 0; i < out.length; i++) if (i !== 8) expect(out[i]).toBeCloseTo(base, 3)
  })
  it('leaves a smooth glide unchanged', () => {
    const f0 = new Float32Array(20)
    for (let i = 0; i < 20; i++) f0[i] = 120 + i * 3  // 120→177, gradual
    const out = smoothOctaves(f0)
    for (let i = 0; i < 20; i++) expect(out[i]).toBeCloseTo(f0[i]!, 3)
  })
})

describe('praatPitchAc synthetic', () => {
  it('tracks a pure 150 Hz sine and a 120→180 Hz glide', () => {
    const sr = 48000, n = sr * 1
    const sine = new Float32Array(n)
    for (let i = 0; i < n; i++) sine[i] = 0.5 * Math.sin(2 * Math.PI * 150 * (i + 0.5) / sr)
    const rs = praatPitchAc(sine, sr, PRAAT_PITCH_DEFAULTS)
    const voiced = [...rs.f0].filter(f => f > 0)
    expect(voiced.length).toBeGreaterThan(rs.f0.length * 0.9)
    for (const f of voiced) expect(Math.abs(1200 * Math.log2(f / 150))).toBeLessThan(5)  // < 5 cents

    const glide = new Float32Array(n)
    for (let i = 0; i < n; i++) { const t = (i + 0.5) / sr; glide[i] = 0.5 * Math.sin(2 * Math.PI * (120 * t + 30 * t * t)) }
    const rg = praatPitchAc(glide, sr, PRAAT_PITCH_DEFAULTS)
    // Instantaneous freq 120→180: each voiced frame's f0 should be within [110, 190].
    for (let i = 0; i < rg.f0.length; i++) if (rg.f0[i]! > 0) { expect(rg.f0[i]!).toBeGreaterThan(110); expect(rg.f0[i]!).toBeLessThan(190) }
  })
})

describe.skipIf(!haveFixtures)('praatPitchAc vs Praat 6.6 (gold standard)', () => {
  const { sampleRate, samples } = haveFixtures ? readWavMono(wavPath) : { sampleRate: 0, samples: new Float32Array(0) }
  const ref = haveFixtures ? readPitchCsv(csvPath) : []

  it('matches Praat: frame grid, voicing, and cents error', () => {
    const out = praatPitchAc(samples, sampleRate, PRAAT_PITCH_DEFAULTS)
    expect(out.f0.length).toBe(ref.length)

    let bothVoiced = 0, voicingAgree = 0, octaveErrors = 0
    const centsErrors: number[] = []
    for (let i = 0; i < ref.length; i++) {
      const rf = ref[i]!.f0, of = out.f0[i]!
      const rv = rf > 0, ov = of > 0
      if (rv === ov) voicingAgree++
      if (rv && ov) {
        bothVoiced++
        const cents = 1200 * Math.log2(of / rf)
        centsErrors.push(Math.abs(cents))
        if (Math.abs(cents) > 600) octaveErrors++  // >½ octave off ⇒ likely octave error
      }
    }
    centsErrors.sort((a, b) => a - b)
    const median = centsErrors[Math.floor(centsErrors.length / 2)] ?? 0
    const p90 = centsErrors[Math.floor(centsErrors.length * 0.9)] ?? 0
    const voicingPct = (voicingAgree / ref.length) * 100
    const octPct = bothVoiced ? (octaveErrors / bothVoiced) * 100 : 0

    console.log(`[praat-pitch] frames=${ref.length} bothVoiced=${bothVoiced} voicingAgree=${voicingPct.toFixed(1)}% ` +
      `medianCents=${median.toFixed(1)} p90Cents=${p90.toFixed(1)} octaveErr=${octPct.toFixed(1)}%`)

    // Our JS port matches Praat 6.6 to well under a cent (only interpolation differs: parabolic vs
    // Praat's sinc), with identical voicing and no octave errors.
    expect(voicingPct).toBeGreaterThan(99)
    expect(median).toBeLessThan(3)
    expect(p90).toBeLessThan(8)
    expect(octPct).toBeLessThan(1)
  })
})
